PlayWithFriends/config/routes.rb
Rails.application.routes.draw do
  resources :servers
  root to: 'servers#index'
  devise_for :users
  resources :users

  # servers routes
  get 'servers/:id/transfer' => 'servers#transfer', as: :transfer_server
  get 'servers/game/:game' => 'servers#index', as: :filter_game

  # invites routes
  get 'invites' => 'invites#index', as: :invites
  get 'invites/:id' => 'invites#show', as: :invite
  get 'servers/:server_id/request' => 'invites#new', as: :invite_to_server
  get 'invites/:id/respond/:response' => 'invites#respond', as: :invite_response
  post 'invites' => 'invites#create', as: :create_invite

  # reputation routes
  get 'reputations' => 'reputations#index', as: :reputations
  get 'reputations/:id' => 'reputations#show', as: :reputation
  get 'reputations/:id/edit' => 'reputations#edit', as: :edit_reputation
  get 'invites/:invite/rate' => 'reputations#new', as: :rate
  post 'reputations' => 'reputations#create', as: :create_reputation
  patch 'reputations/:id' => 'reputations#update', as: :update_reputation
end

PlayWithFriends/app/models/reputation.rb
class Reputation < ActiveRecord::Base
  belongs_to :user, :primary_key => "id", :foreign_key => "to_id", :required => true
  belongs_to :server, :required => true
  belongs_to :user, :primary_key => "id", :foreign_key => "from_id", :required => true

  validates :rating, :message, presence: true
  validates :rating, :numericality => {:greater_than => 0, :less_than_or_equal_to => 5}
end

PlayWithFriends/app/controllers/reputations_controller.rb
class ReputationsController < ApplicationController
  before_action :set_reputation, only: [:show, :edit, :update]
  before_filter :authenticate_user!

  # GET /reputations
  # GET /reputations.json
  def index
    @from = Reputation.where(from_id: current_user.id)
    @to = Reputation.where(to_id: current_user.id)
  end

  # GET /reputations/1
  # GET /reputations/1.json
  def show
  end

  # GET /reputations/new
  def new
    @reputation = Reputation.new
  end

  # GET /reputations/1/edit
  def edit
  end

  # POST /reputations
  # POST /reputations.json
  def create
    @reputation = Reputation.new(reputation_params)

    respond_to do |format|
      if @reputation.save
        format.html { redirect_to reputations_url, notice: 'Reputation was successfully created.' }
        format.json { render :show, status: :created, location: @reputation }
      else
        @server_owner = User.find_by_email(Server.find_by_id(@reputation.server_id).owner).id
        format.html { redirect_to rate_url(Invite.find_by(server_id: @reputation.server_id, to_id: @server_owner, from_id: @reputation.to_id == @server_owner ? @reputation.from_id : @reputation.to_id)), alert: @reputation.errors.full_messages.to_sentence }
        format.json { render json: @reputation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reputations/1
  # PATCH/PUT /reputations/1.json
  def update
    respond_to do |format|
      if @reputation.update(reputation_params)
        format.html { redirect_to reputations_url, notice: 'Reputation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reputation }
      else
        format.html { render :edit }
        format.json { render json: @reputation.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reputation
      @reputation = Reputation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reputation_params
      params.require(:reputation).permit(:to_id, :from_id, :server_id, :rating, :message)
    end
end

PlayWithFriends/app/helpers/reputations_helper.rb
module ReputationsHelper
end

PlayWithFriends/app/views/reputations/_form.html.erb
<%= form_for(@reputation) do |f| %>
    <%
       if (@reputation.new_record?)
         @invite = Invite.find_by_id(params[:invite])
         @server = @invite.server_id
         @from = current_user.id
         @to = (@invite.to_id == @from ? @invite.from_id : @invite.to_id)
       else
         @server = @reputation.server_id
         @from = @reputation.from_id
         @to = @reputation.to_id
       end
    %>

    <div class="field">
      <%= f.label :to_id, "Leaving reputation for '" + User.find_by_id(@to).email + "'!" %><br>
      <%= f.hidden_field :server_id, :value => @server, :readonly => true %>
      <%= f.hidden_field :to_id, :value => @to, :readonly => true %>
      <%= f.hidden_field :from_id, :value => @from, :readonly => true %>
    </div>

    <div class="field">
      <%= f.label :rating %><br>
      <%= f.radio_button :rating, 1 %>
      <%= f.label :rating_1, "1 <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>".html_safe %>
      <%= f.radio_button :rating, 2 %>
      <%= f.label :rating_2, "2 <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>".html_safe %>
      <%= f.radio_button :rating, 3 %>
      <%= f.label :rating_3, "3 <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>".html_safe %>
      <%= f.radio_button :rating, 4 %>
      <%= f.label :rating_4, "4 <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>".html_safe %>
      <%= f.radio_button :rating, 5 %>
      <%= f.label :rating_5, "5 <span class=\"glyphicon glyphicon-star\" aria-hidden=\"true\"></span>".html_safe %>
    </div>

    <div class="field">
      <%= f.label :message %><br>
      <%= f.text_area :message, :cols => 60 %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

PlayWithFriends/app/views/reputations/edit.html.erb
<h1>Editing Reputation</h1>

<% if @reputation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reputation.errors.count, "error") %> prohibited this reputation from being saved:</h2>

      <ul>
        <% @reputation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% elsif current_user.id == @reputation.from_id %>
    <%= render 'form' %>
<% else %>
    <p>You do not have permission to edit this reputation!</p>
<% end %>

<%= link_to 'Show', @reputation %> |
<%= link_to 'Back', reputations_path %>

PlayWithFriends/app/views/reputations/index.html.erb
<h1>Reputation</h1>
<div class="panel panel-primary">
  <div class="panel-heading"><h3 class="panel-title">Reputation Given By You</h3></div>
  <div class="panel-body">
    <table class="table table-condensed table-hover">
      <thead>
      <tr>
        <th>To</th>
        <th>Server</th>
        <th>Your Role</th>
        <th>Rating</th>
      </tr>
      </thead>

      <tbody style="cursor: pointer; cursor: hand;">
      <% @from.each do |reputation|
        @server = Server.find_by_id(reputation.server_id)
      %>
          <tr data-link="<%= reputation_path(reputation) %>">
            <td><%= User.find_by_id(reputation.to_id).email %></td>
            <td><%= @server.title %></td>
            <td><%= @server.owner == current_user.email ? 'Owner' : 'Player' %></td>
            <td>
              <% reputation.rating.times do |i| %>
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
              <% end %>
              <% (5 - reputation.rating).times do |i| %>
                  <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="panel panel-primary">
  <div class="panel-heading"><h3 class="panel-title">Reputation Given To You</h3></div>
  <div class="panel-body">
    <table class="table table-condensed table-hover">
      <thead>
      <tr>
        <th>From</th>
        <th>Server</th>
        <th>Their Role</th>
        <th>Rating</th>
      </tr>
      </thead>

      <tbody style="cursor: pointer; cursor: hand;">
      <% @to.each do |reputation|
        @server = Server.find_by_id(reputation.server_id)

        # temp server
        if (@server == nil)
          @server = Server.new
          @server.title='Deleted'
          end
         @user = User.find_by_id(reputation.from_id)
      %>
          <tr data-link="<%= reputation_path(reputation) %>">
            <td><%= @user.email %></td>
            <td><%= @server.title %></td>
            <td><%= @server.owner == @user.email ? 'Owner' : 'Player' %></td>
            <td>
              <% reputation.rating.times do |i| %>
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
              <% end %>
              <% (5 - reputation.rating).times do |i| %>
                  <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= link_to 'Back to Servers', servers_path, {:class => 'btn btn-default'} %>

PlayWithFriends/app/views/reputations/new.html.erb
<h1>New Reputation</h1>

<% if (params[:invite] == nil) %>
    <div class="alert alert-danger">No invite for rating!</div>
<% else
     @invite = Invite.find_by_id(params[:invite])
     @from = current_user.id
     @to = (@invite.to_id == @from ? @invite.from_id : @invite.to_id)
     if (Reputation.find_by(server_id: @invite.server_id, from_id: @from, to_id: @to) != nil) %>
        <div class="alert alert-danger">You have already rated this user!</div>
    <% else %>
        <%= render 'form' %>
    <% end %>
<% end %>
    <%= link_to 'Back', invite_path(params[:invite]) %>

PlayWithFriends/app/views/reputations/show.html.erb
<%
   @rating = @reputation.rating
   @from = User.find_by_id(@reputation.from_id)
   @server = Server.find_by_id(@reputation.server_id)
%>
<br>
<div class="panel panel-info">
  <div class="panel-heading"><h3 class="panel-title">View Reputation</h3></div>
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-2"><strong>From</strong></div>
      <div class="col-sm-10">
        <%= link_to @from.email, user_path(@from) %><br>
        <%= if (!@server == nil)
              (@from.email == @server.owner ? 'Owner of ' : 'Player on ')
              link_to(@server.title, server_path(@server)).html_safe
            end
        %>
      </div>
      <div class="col-sm-2"><strong>Rating</strong></div>
      <div class="col-sm-10">
        <% @reputation.rating.times do |i| %>
            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <% end %>
        <% (5 - @reputation.rating).times do |i| %>
            <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
        <% end %>
      </div>
      <div class="col-sm-2"><strong>Message</strong></div>
      <div class="col-sm-10">
        <pre><%= @reputation.message %></pre>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Edit', edit_reputation_path(@reputation), {:class => 'btn btn-warning'} %>&nbsp;
<%= link_to 'Back', reputations_path, {:class => 'btn btn-default'} %>