PlayWithFriends/config/routes.rb
Rails.application.routes.draw do
  resources :servers
  root to: 'servers#index'
  devise_for :users
  resources :users

  # servers routes
  get 'servers/:id/transfer' => 'servers#transfer', as: :transfer_server
  get 'servers/game/:game' => 'servers#index', as: :filter_game

  # invites routes
  get 'invites' => 'invites#index', as: :invites
  get 'invites/:id' => 'invites#show', as: :invite
  get 'servers/:server_id/request' => 'invites#new', as: :invite_to_server
  get 'invites/:id/respond/:response' => 'invites#respond', as: :invite_response
  post 'invites' => 'invites#create', as: :create_invite

  # reputation routes
  get 'reputations' => 'reputations#index', as: :reputations
  get 'reputations/:id' => 'reputations#show', as: :reputation
  get 'reputations/:id/edit' => 'reputations#edit', as: :edit_reputation
  get 'invites/:invite/rate' => 'reputations#new', as: :rate
  post 'reputations' => 'reputations#create', as: :create_reputation
  patch 'reputations/:id' => 'reputations#update', as: :update_reputation
end

PlayWithFriends/app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :user, :primary_key => "email", :foreign_key => "owner", :required => true
  belongs_to :game, :primary_key => "id", :foreign_key => "game_id", :required => true
  has_many :invites
  has_many :reputations

  validates :title, :description, :ip, presence: true
  validates :title, :ip, uniqueness: true
end

PlayWithFriends/app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :transfer, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /servers
  # GET /servers.json
  def index
    @servers = params[:game] ? Server.where(game_id: params[:game]) : Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # GET /servers/1/transfer
  def transfer
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:owner, :game_id, :up_votes, :down_votes, :title, :description, :ip, :private)
    end
end

PlayWithFriends/app/helpers/servers_helper.rb
module ServersHelper
end

PlayWithFriends/app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
    <% if @server.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

          <ul>
            <% @server.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <table class="table-condensed">
      <tbody>
      <tr>
        <td><%= f.label :owner %></td>
        <td>
          <%= f.email_field :owner, :value => current_user.email, :readonly => true, :size => 60 %>

          <% if !@server.new_record? %>
            <%= link_to 'Transfer', transfer_server_path(@server), :class => "btn btn-danger btn-xs" %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :game_id %></td>
        <td><%= f.collection_select :game_id, Game.all, :id, :name, {:include_blank => true} %></td>
      </tr>
      <tr>
        <td><%= f.label :title %></td>
        <td><%= f.text_field :title, :size => 60 %></td>
      </tr>
      <tr>
        <td><%= f.label :ip %></td>
        <td>
          <%= f.text_field :ip, :size => 60 %><br>
          <%= f.label :private %>&nbsp;<%= f.check_box :private, :value => @server.private %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :description %></td>
        <td><%= f.text_area :description, :cols => 60 %></td>
      </tr>
      </tbody>
    </table>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

PlayWithFriends/app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
        <% @server.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% elsif current_user.email == @server.owner %>
    <%= render 'form' %>
<% else %>
    <p>You do not have permission to edit this server!</p>
<% end %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

PlayWithFriends/app/views/servers/index.html.erb
<h1>Listing <%= params[:game] ? Game.find_by_id(params[:game]).name : '' %> Servers</h1>

<table class="table table-condensed table-hover">
  <thead>
  <tr>
    <th>Game</th>
    <th>Title</th>
    <th>Visibility</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody style="cursor: pointer; cursor: hand;">
  <% @servers.each do |server| %>
      <tr data-link="<%= server_path(server) %>">
        <td><%= Game.find_by_id(server.game_id).name %></td>
        <td><%= server.title %></td>
        <td><%= server.private? ? raw("Invite-Only") : raw("Public") %></td>
        <% if current_user && current_user.email == server.owner %>
            <td><%= link_to 'Edit', edit_server_path(server), :class => "btn btn-default btn-xs" %></td>
            <td><%= link_to 'Destroy', server, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger btn-xs" %></td>
        <% else %>
            <td colspan="2"></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

PlayWithFriends/app/views/servers/new.html.erb
<h1>New Server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

PlayWithFriends/app/views/servers/show.html.erb
<% @owner = User.find_by_email(@server.owner) %>
<h1>View Server</h1>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @server.title + '(' + (@server.private? ? 'Invite-Only' : 'Public') + ')' %></h3>
  </div>
  <div class="panel-body">
    <div class="col-sm-2"><strong>Owner</strong></div>
    <div class="col-sm-10"><%= link_to(@server.owner, user_path(@owner)) %></div>

    <div class="col-sm-2"><strong>Game</strong></div>
    <div class="col-sm-10">
      <% @game = Game.find_by_id(@server.game_id) %>
      <%= ('<a href="' + @game.website + '" target="_blank">' + @game.name + '</a>').html_safe %>
    </div>

    <div class="col-sm-2"><strong>Description</strong></div>
    <div class="col-sm-10">
      <pre><%= @server.description %></pre>
    </div>

    <% if !@server.private %>
        <div class="col-sm-2"><strong>IP Address</strong></div>
        <div class="col-sm-10"><%= @server.ip %></div>
    <% end %>

    <%
       @rating = Reputation.where(to_id: @owner.id, server_id: @server.id).average(:rating).to_f

       # noinspection RubyArgCount
       @rating = @rating.round.to_i
    %>

    <div class="col-sm-2"><strong>Average Rating</strong></div>
    <div class="col-sm-10">
      <% @rating.times do |i| %>
          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
      <% end %>
      <% (5 - @rating).times do |i| %>
          <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>
</div>
<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Reputation</h3>
  </div>
  <div class="panel-body">
    <div class="container-fluid">
      <%
         @reputations = Reputation.where(server_id: @server.id, to_id: User.find_by_email(@server.owner))
         @reputations.each do |rep|
           @rating = rep.rating
           @from = User.find_by_id(rep.from_id)
      %>

          <div class="row">
            <div class="col-sm-2"><strong>From</strong></div>
            <div class="col-sm-10">
              <%= link_to(@from.email, user_path(@from)) %>
            </div>
            <div class="col-sm-2"><strong>Rating</strong></div>
            <div class="col-sm-10">
              <% @rating.times do |i| %>
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
              <% end %>
              <% (5 - @rating).times do |i| %>
                  <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
              <% end %>
            </div>
            <div class="col-sm-2"><strong>Message</strong></div>
            <div class="col-sm-10">
              <pre><%= rep.message %></pre>
            </div>
          </div>
          <hr>
      <% end %>
    </div>
  </div>
</div>
<% if current_user %>
    <% if current_user.email == @server.owner %>
        <%= link_to 'Edit', edit_server_path(@server), {:class => 'btn btn-warning'} %>&nbsp;<%= link_to 'Destroy', @server, method: :delete, :class => 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
    <% elsif @server.private? %>
        <% @invite = Invite.find_by(from_id: current_user.id, server_id: @server.id) %>

        <% if @invite == nil %>
            <%= link_to 'Request Invite', invite_to_server_path(@server), {:class => 'btn btn-primary'} %>
        <% else %>
            <%= link_to 'Check Invite Status', invite_path(Invite.find_by(from_id: current_user.id, server_id: @server.id)), :class => 'btn btn-info' %>
            <br><br>
        <% end %>
    <% end %>
<% end %>
<%= link_to 'Back', servers_path, {:class => 'btn btn-default'} %>

PlayWithFriends/app/views/servers/transfer.html.erb
<h1>Transfer Server Ownership</h1>
<% if current_user.email == @server.owner %>
    <%= form_for(@server) do |f| %>
        <div class="field">
          <%= f.label :owner, "New Owner Email" %><br>
          <%= f.email_field :owner, :value => current_user.email, :size => 60 %>
        </div>

        <div class="actions">
          <%= f.submit data: { confirm: "Are you sure your wish to transfer ownership of the server?" } %>
        </div>
    <% end %>
<% else %>
    <p>You do not have permission to edit this server!</p>
<% end %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>