PlayWithFriends/config/routes.rb
Rails.application.routes.draw do
  resources :servers
  root to: 'servers#index'
  devise_for :users
  resources :users

  # servers routes
  get 'servers/:id/transfer' => 'servers#transfer', as: :transfer_server
  get 'servers/game/:game' => 'servers#index', as: :filter_game

  # invites routes
  get 'invites' => 'invites#index', as: :invites
  get 'invites/:id' => 'invites#show', as: :invite
  get 'servers/:server_id/request' => 'invites#new', as: :invite_to_server
  get 'invites/:id/respond/:response' => 'invites#respond', as: :invite_response
  post 'invites' => 'invites#create', as: :create_invite

  # reputation routes
  get 'reputations' => 'reputations#index', as: :reputations
  get 'reputations/:id' => 'reputations#show', as: :reputation
  get 'reputations/:id/edit' => 'reputations#edit', as: :edit_reputation
  get 'invites/:invite/rate' => 'reputations#new', as: :rate
  post 'reputations' => 'reputations#create', as: :create_reputation
  patch 'reputations/:id' => 'reputations#update', as: :update_reputation
end

PlayWithFriends/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

PlayWithFriends/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

PlayWithFriends/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li role="presentation" class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
    Games <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <% Game.all.each do |g| %>
    <li><%= link_to g.name, filter_game_path(g.id) %></li>
    <% end %>
  </ul>
</li>
<% if user_signed_in? %>
    <li>
      <a href="<%= invites_path %>">Invites <span class="badge alert-info">
    <%=
        @invites = Invite.where("to_id = '" + current_user.id.to_s + "' AND read = 'f'")
        if (@invites != nil)
          @invites.count
        else
          '0'
        end
    %></span></a>
    </li>
    <li><%= link_to 'Reputation', reputations_path %></li>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

PlayWithFriends/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Play With Friends" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Play With Friends" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>