PlayWithFriends/config/routes.rb
Rails.application.routes.draw do
  resources :servers
  root to: 'servers#index'
  devise_for :users
  resources :users

  # servers routes
  get 'servers/:id/transfer' => 'servers#transfer', as: :transfer_server
  get 'servers/game/:game' => 'servers#index', as: :filter_game

  # invites routes
  get 'invites' => 'invites#index', as: :invites
  get 'invites/:id' => 'invites#show', as: :invite
  get 'servers/:server_id/request' => 'invites#new', as: :invite_to_server
  get 'invites/:id/respond/:response' => 'invites#respond', as: :invite_response
  post 'invites' => 'invites#create', as: :create_invite

  # reputation routes
  get 'reputations' => 'reputations#index', as: :reputations
  get 'reputations/:id' => 'reputations#show', as: :reputation
  get 'reputations/:id/edit' => 'reputations#edit', as: :edit_reputation
  get 'invites/:invite/rate' => 'reputations#new', as: :rate
  post 'reputations' => 'reputations#create', as: :create_reputation
  patch 'reputations/:id' => 'reputations#update', as: :update_reputation
end

PlayWithFriends/app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user, :primary_key => "id", :foreign_key => "to_id", :required => true
  belongs_to :server, :required => true
  belongs_to :user, :primary_key => "id", :foreign_key => "from_id", :required => true

  validates :message, presence: true
end

PlayWithFriends/app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :respond, :destroy]
  before_filter :authenticate_user!

  # GET /invites
  # GET /invites.json
  def index
    @incoming = Invite.where("to_id = '" + current_user.id.to_s + "'")
    @outgoing = Invite.where("from_id = '" + current_user.id.to_s + "'")
  end

  # GET /invites/1
  # GET /invites/1.json
  def show
  end

  # GET /invites/new
  def new
    @invite = Invite.new
  end

  def respond
    @invite = Invite.find_by_id(params[:id])
    @invite.accepted=params[:response]
    @invite.active=false

    respond_to do |format|
      if @invite.save
        format.html { redirect_to invite_path(@invite), notice: 'Invite ' + (@invite.accepted? ? 'accepted' : 'rejected') + '!' }
        format.json { render :show, status: :ok, location: @invite }
      else
        format.html { redirect_to invite_path(@invite), alert: @invite.errors.full_messages.to_sentence }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /invites
  # POST /invites.json
  def create
    @invite = Invite.new(invite_params)

    respond_to do |format|
      if @invite.save
        @server = Server.find_by_id(@invite.server_id)
        format.html { redirect_to server_path(@server), notice: 'Invite to \'' + @server.title + '\' pending.' }
        format.json { render :show, status: :created, location: @invite }
      else
        format.html { redirect_to invite_to_server_url(Server.find_by_id(@invite.server_id)), alert: @invite.errors.full_messages.to_sentence }
        format.json { render json: @invite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invites/1
  # DELETE /invites/1.json
  def destroy
    @invite.destroy
    respond_to do |format|
      format.html { redirect_to invites_url, notice: 'Invite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_invite
    @invite = Invite.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invite_params
    params.require(:invite).permit(:to_id, :from_id, :server_id, :message, :read, :active, :accepted)
  end
end

PlayWithFriends/app/helpers/invites_helper.rb
module InvitesHelper
end

PlayWithFriends/app/views/invites/_form.html.erb
<%= form_for(@invite) do |f| %>
    <% if @invite.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@invite.errors.count, "error") %> prohibited this invite from being saved:</h2>

          <ul>
            <% @invite.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% @server = Server.find(params[:server_id]) %>

    <%= f.label :to_id, "Request Invite to server '" + @server.title + "'" %><br>
    <%= f.hidden_field :server_id, :value => @server.id, :readonly => true %>
    <%= f.hidden_field :to_id, :value => User.find_by_email(@server.owner).id, :readonly => true %>
    <%= f.hidden_field :from_id, :value => current_user.id, :readonly => true %>
    <%= f.hidden_field :read, :value => false, :readonly => true %>
    <%= f.hidden_field :active, :value => true, :readonly => true %>
    <%= f.hidden_field :accepted, :value => false, :readonly => true %>

    <div class="field">
      <%= f.label :message %><br>
      <%= f.text_area :message, :cols => 60 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

PlayWithFriends/app/views/invites/index.html.erb
    <h1>Invites</h1>
    <div class="panel panel-primary">
      <div class="panel-heading"><h3 class="panel-title">Incoming</h3></div>
      <div class="panel-body">

        <table class="table table-condensed table-hover">
          <thead>
          <tr>
            <th>From</th>
            <th>Server</th>
          </tr>
          </thead>

          <tbody style="cursor: pointer; cursor: hand;">
          <% @incoming.each do |invite| %>
              <%
                 @class = ""
                 if (!invite.read?)
                   @class = "info"
                 elsif (!invite.active? && invite.accepted?)
                   @class = "success"
                 elsif (!invite.active? && !invite.accepted?)
                   @class = "danger"
                 end
                 @server = Server.find_by_id(invite.server_id)

                 if (@server == nil)
                   @server = Server.new
                   @server.title='Deleted'
                 end
              %>
              <tr class="<%= @class %>" data-link="<%= invite_path(invite) %>">
                <td><%= User.find_by_id(invite.from_id).email %></td>
                <td><%= @server.title %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="panel panel-primary">
      <div class="panel-heading"><h3 class="panel-title">Outgoing</h3></div>
      <div class="panel-body">

        <table class="table table-condensed table-hover">
          <thead>
          <tr>
            <th>Server</th>
            <th>Owner</th>
          </tr>
          </thead>

          <tbody style="cursor: pointer; cursor: hand;">
          <% @outgoing.each do |invite| %>
              <%
                 @class = ""
                 if (!invite.active? && invite.accepted?)
                   @class = "success"
                 elsif (!invite.active? && !invite.accepted?)
                   @class = "danger"
                 end
                 @server = Server.find_by_id(invite.server_id)

                 if (@server == nil)
                   @server = Server.new
                   @server.title='Deleted'
                   @server.owner='Unknown'
                 end
              %>
              <tr class="<%= @class %>" data-link="<%= invite_path(invite) %>">
                <td><%= @server.title %></td>
                <td><%= @server.owner %></td>
              </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>

PlayWithFriends/app/views/invites/new.html.erb
<h1>New Invite</h1>

<% @server = Server.find_by_id(params[:server_id])
   if (@server == nil) %>
    <div class="alert alert-danger">No server selected!</div>
<% elsif (@server.owner == current_user.email) %>
    <div class="alert alert-danger">You cannot request invite to your own server!</div>
<% elsif (Invite.find_by(from_id: current_user.id, server_id: @server.id) != nil) %>
    <div class="alert alert-danger">You already have an invite open to this server!</div>
<% else %>
    <%= render 'form' %>
<% end %>
<%= link_to 'Back', invites_path %>

PlayWithFriends/app/views/invites/show.html.erb
<br>
<div class="panel panel-primary">
  <div class="panel-heading"><h3 class="panel-title">View Invite</h3></div>
  <div class="panel-body">
    <% # when read by invite's target, mark as read
       if (current_user.id == @invite.to_id)
         @invite.read=true
         @invite.save
       end

       if (@invite.to_id == current_user.id)
         @to = User.find_by_id(@invite.from_id)
    %>
        <div class="col-sm-2"><strong>From</strong></div>
        <div class="col-sm-10"><%= link_to @to.email, user_path(@to) %></div>

        <div class="col-sm-2"><strong>Average Rating</strong></div>
        <div class="col-sm-10">
          <%
             @rating = Reputation.includes(:server).references(:servers).where.not(servers: {owner: @to.email}).where(to_id: @to.id,).average(:rating).to_f

             # noinspection RubyArgCount
             @rating = @rating.round.to_i
          %>
          <% @rating.times do |i| %>
              <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
          <% end %>
          <% (5 - @rating).times do |i| %>
              <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
          <% end %>
          &nbsp;(<%= link_to 'View', user_path(@to) %>)
        </div>
    <%
       end
       @server = Server.find_by_id(@invite.server_id)
    %>

    <div class="col-sm-2"><strong>To</strong></div>
    <div class="col-sm-10"><%= @server.title %></div>

    <div class="col-sm-2"><strong>Message</strong></div>
    <div class="col-sm-10">
      <pre><%= @invite.message %></pre>
    </div>

    <% if (@invite.to_id == current_user.id) %>
        <div class="container-fluid">
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @invite.active? ? 'Respond' : 'Change Response' %></h3>
            </div>
            <div class="panel-body">

              <%= link_to @invite.accepted? ? 'Accepted' : 'Accept', invite_response_path(@invite.id, 'true'), {:class => 'btn ' + (@invite.active? || @invite.accepted? ? 'btn-success' : 'btn-default')} %>
              <%= link_to !@invite.accepted? && !@invite.active? ? 'Rejected' : 'Reject', invite_response_path(@invite.id, 'false'), {:class => 'btn ' + (@invite.active? || !@invite.accepted? ? 'btn-danger' : 'btn-default')} %>
            </div>
          </div>
        </div>
        <%= if (@invite.accepted? && Reputation.find_by(to_id: @to.id, from_id: current_user.id, server_id: @invite.server_id) == nil)
              link_to 'Rate User', rate_path(@invite), {:class => "btn btn-primary"}
            end
        %>
    <% else %>
        <div class="col-sm-2"><strong>Status</strong></div>
        <div class="col-sm-10">
          <%=
              if (@invite.active?)
                '<div class="alert alert-warning" role="alert">Awaiting Response</div>'.html_safe
              elsif (@invite.accepted?)
                '<div class="alert alert-success" role="alert">Accepted!</div>'.html_safe
              else
                '<div class="alert alert-danger" role="alert">Rejected.</div>'.html_safe
              end
          %>
        </div>
        <% if (@invite.accepted?) %>
            <div class="col-sm-2"><strong>IP Address</strong></div>
            <div class="col-sm-10"><%= @server.ip %></div>

            <div class="col-sm-12">&nbsp;</div>
            <% if (Reputation.find_by(to_id: User.find_by_email(@server.owner).id, from_id: current_user.id, server_id: @invite.server_id) == nil) %>
                <div class="col-sm-12"><%= link_to 'Rate Server', rate_path(@invite), {:class => "btn btn-primary"} %></div>
            <% end %>
        <% end %>

    <% end %>

  </div>
</div>
<%= link_to 'Back', invites_path, {:class => "btn btn-default"} %>